package com.binbash.mobigo.domain.enumeration;

/**
 * The NotificationType enumeration.
 */
public enum NotificationType {
    BOOKING_RECEIVED,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TRIP_MODIFIED,
    TRIP_CANCELLED,
    TRIP_REMINDER,
    RATING_RECEIVED,
    MESSAGE_RECEIVED,
    PAYMENT_REQUESTED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    PAYMENT_DISBURSED,
    IDENTITY_VERIFIED,
    IDENTITY_REJECTED,
}
