package com.binbash.mobigo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GroupAuthorityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAuthorityAllPropertiesEquals(GroupAuthority expected, GroupAuthority actual) {
        assertGroupAuthorityAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupAuthorityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAuthorityAllUpdatablePropertiesEquals(GroupAuthority expected, GroupAuthority actual) {
        assertGroupAuthorityUpdatableFieldsEquals(expected, actual);
        assertGroupAuthorityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAuthorityAutoGeneratedPropertiesEquals(GroupAuthority expected, GroupAuthority actual) {
        assertThat(actual)
            .as("Verify GroupAuthority auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAuthorityUpdatableFieldsEquals(GroupAuthority expected, GroupAuthority actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAuthorityUpdatableRelationshipsEquals(GroupAuthority expected, GroupAuthority actual) {
        assertThat(actual)
            .as("Verify GroupAuthority relationships")
            .satisfies(a -> assertThat(a.getAuthority()).as("check authority").isEqualTo(expected.getAuthority()))
            .satisfies(a -> assertThat(a.getGroup()).as("check group").isEqualTo(expected.getGroup()));
    }
}
