package com.binbash.mobigo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAllPropertiesEquals(Group expected, Group actual) {
        assertGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAllUpdatablePropertiesEquals(Group expected, Group actual) {
        assertGroupUpdatableFieldsEquals(expected, actual);
        assertGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAutoGeneratedPropertiesEquals(Group expected, Group actual) {
        assertThat(actual)
            .as("Verify Group auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupUpdatableFieldsEquals(Group expected, Group actual) {
        assertThat(actual)
            .as("Verify Group relevant properties")
            .satisfies(a -> assertThat(a.getGroupName()).as("check groupName").isEqualTo(expected.getGroupName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupUpdatableRelationshipsEquals(Group expected, Group actual) {
        // empty method
    }
}
