package com.binbash.mobigo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GroupMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupMemberAllPropertiesEquals(GroupMember expected, GroupMember actual) {
        assertGroupMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupMemberAllUpdatablePropertiesEquals(GroupMember expected, GroupMember actual) {
        assertGroupMemberUpdatableFieldsEquals(expected, actual);
        assertGroupMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupMemberAutoGeneratedPropertiesEquals(GroupMember expected, GroupMember actual) {
        assertThat(actual)
            .as("Verify GroupMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupMemberUpdatableFieldsEquals(GroupMember expected, GroupMember actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupMemberUpdatableRelationshipsEquals(GroupMember expected, GroupMember actual) {
        assertThat(actual)
            .as("Verify GroupMember relationships")
            .satisfies(a -> assertThat(a.getGroup()).as("check group").isEqualTo(expected.getGroup()));
    }
}
