package com.binbash.mobigo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StepAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepAllPropertiesEquals(Step expected, Step actual) {
        assertStepAutoGeneratedPropertiesEquals(expected, actual);
        assertStepAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepAllUpdatablePropertiesEquals(Step expected, Step actual) {
        assertStepUpdatableFieldsEquals(expected, actual);
        assertStepUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepAutoGeneratedPropertiesEquals(Step expected, Step actual) {
        assertThat(actual)
            .as("Verify Step auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepUpdatableFieldsEquals(Step expected, Step actual) {
        assertThat(actual)
            .as("Verify Step relevant properties")
            .satisfies(a -> assertThat(a.getVille()).as("check ville").isEqualTo(expected.getVille()))
            .satisfies(a -> assertThat(a.getHeureDepart()).as("check heureDepart").isEqualTo(expected.getHeureDepart()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepUpdatableRelationshipsEquals(Step expected, Step actual) {
        assertThat(actual)
            .as("Verify Step relationships")
            .satisfies(a -> assertThat(a.getTrajet()).as("check trajet").isEqualTo(expected.getTrajet()));
    }
}
